cherr0/Capstone-TMATE

- src/main/resources/static/css/hotplace.css
- src/main/resources/templates/hotplace.html
핫플레이스 화면에서 웹브라우저가 작아질 시 리스트가 보이지않던 부분 및 불필요한 부분 수정
> 02/22 핫플레이스 수정

- src/main/resources/static/js/main.js
- src/main/resources/templates/index.html
- src/main/resources/templates/main.html
- src/main/resources/templates/userDetail.html
- src/main/resources/templates/userList.html
>  02/24 타임리프 작성 및 html수정 

- src/main/resources/static/js/main.js
- src/main/resources/static/vendor/animsition/animsition.min.js
링크 이동 시 fade in/out하던 애니메이션 삭제
> 02/24 화면전환 애니메이션 삭제

- src/main/resources/templates/eventDetail.html
- src/main/resources/templates/eventModify.html
- src/main/resources/templates/noticeDetail.html
- src/main/resources/templates/noticeModify.html
이벤트/공지 글 조회, 글 수정 타임리프작성 및 버튼 id추가
> 02/24 타임리프, 버튼 id 추가

- src/main/resources/templates/approvalList.html
- src/main/resources/templates/eventDetail.html
- src/main/resources/templates/eventList.html
- src/main/resources/templates/eventModify.html
- src/main/resources/templates/eventWrite.html
- src/main/resources/templates/hotplace.html
- src/main/resources/templates/noticeDetail.html
- src/main/resources/templates/noticeList.html
- src/main/resources/templates/noticeModify.html
- src/main/resources/templates/noticeWrite.html
승인관리, 핫플레이스, 공지/이벤트 리스트,조회,작성,수정 타임리프 작성
id 부여 및 수정
> html 타임리프 수정 및 id 수정

- src/main/resources/templates/eventList.html
- src/main/resources/templates/noticeList.html
- src/main/resources/templates/userList.html
공지 리스트, 이벤트 리스트, 유저 리스트 타임리프 작성 및 수정
> 02/25 타임리프 작성 및 수정

- src/main/resources/mybatis/MemberMapper.xml
- src/main/resources/static/css/approvalList.css
- src/main/resources/templates/approvalList.html
- src/main/resources/templates/eventModify.html
- src/main/resources/templates/main.html
- src/main/resources/templates/noticeModify.html
basic.html 수정으로 인한 메인페이지 수정
memberMapper 아직 m으로 바뀌지않은 u를 m으로 수정
> 02/26 메인페이지 html 수정, memberMapper 수정

- src/main/resources/mybatis/MemberMapper.xml
- src/main/resources/templates/main.html
basic.html 수정으로 인한 메인페이지 수정
memberMapper 아직 m으로 바뀌지않은 u를 m으로 수정
> 메인페이지 html 수정, membermapper 수정

- src/main/resources/templates/approvalList.html
- src/main/resources/templates/eventDetail.html
- src/main/resources/templates/eventWrite.html
이벤트 디테일, 작성 html 수정 및 id 수정
승인관리 html 수정
> 02/26 html 수정 및 id 수정

- src/main/java/com/tmate/web/MemberController.java
- src/main/resources/templates/eventList.html
- src/main/resources/templates/eventModify.html
- src/main/resources/templates/userDetail.html
MemberController 수정
userDetail 타임리프 설정
eventModfidy.html 수정
eventList.html 수정
> 21/02/26 MemberController 수정 및 html 수정

- src/main/resources/static/css/approvalList.css
- src/main/resources/static/js/main.js
- src/main/resources/templates/approvalList.html
- src/main/resources/templates/hotplace.html
- src/main/resources/templates/noticeDetail.html
- src/main/resources/templates/noticeList.html
baisc 수정으로인한  승인관리 핫플레이스 html 수정 , 차트 js 값 수정
> 02/26 승인관리 핫플레이스 수정, 메인 차트js 수정

- src/main/resources/static/css/approvalList.css
- src/main/resources/static/css/hotplace.css
- src/main/resources/templates/approvalList.html
- src/main/resources/templates/hotplace.html
hotplace.html
approvalList.html 디자인수정
hotplace.css
approvalList.css css 추가
> 03/01 핫플레이스 검색창, 승인괸리 디자인 수정

- src/main/resources/static/css/hotplace.css
- src/main/resources/templates/hotplace.html
> 03/05 핫플레이스 화면 깨짐 수정

- build.gradle
- src/main/resources/static/css/main.css
- src/main/resources/templates/index.html
> 03/05 메인페이지 폰트 수정

- build.gradle
- src/main/resources/static/css/theme.css
- src/main/resources/templates/index.html
> 21/03/08 색상변경

- src/main/java/com/tmate/mapper/EventMapper.java
- src/main/java/com/tmate/service/EventService.java
- src/main/java/com/tmate/service/EventServiceImpl.java
- src/main/java/com/tmate/web/EventApiController.java
- src/main/resources/application.properties
- src/main/resources/mybatis/EventMapper.xml
- src/main/resources/static/js/app/event.js
> 이벤트 삭제 로직 수정

- src/main/resources/static/js/main.js
- src/main/resources/templates/admin/main.html
- src/main/resources/templates/user/pointDetail.html
사용자페이지 포인트내역 제작 및 chartjs 수정
전체 html 타이틀 글자색 수정
> 21/03/12 사용자페이지 포인트내역 제작

- src/main/resources/templates/layout/basic2.html
> 21/03/11 사용자페이지 레이아웃 제작

- src/main/resources/static/js/main.js
- src/main/resources/templates/user/historyDetail.html
> 21/03/14 이용내역 페이지 제작

- src/main/java/com/tmate/service/UserService.java
- src/main/java/com/tmate/service/UserServiceImpl.java
- src/main/java/com/tmate/web/IndexController.java
- src/main/java/com/tmate/web/UserController.java
- src/main/resources/mybatis/UserMainMapper.xml
- src/main/resources/templates/index.html
- src/main/resources/templates/layout/basic2.html
- src/main/resources/templates/user/historyDetail.html
- src/main/resources/templates/user/main.html
- src/main/resources/templates/user/paymentDetail.html
- src/main/resources/templates/user/pointDetail.html
컨트롤러, 매퍼, 서비스, 페이지 네이션, 타임리프 처리,
> 차트 제외하고 작업 완료

- src/main/resources/static/css/theme.css
- src/main/resources/templates/user/paymentDetail.html
- src/main/resources/templates/user/profileModify.html
> 21/03/15 프로필 정보 제작 및 결제내역 내용 수정

- src/main/resources/static/css/sidebar.css
- src/main/resources/static/js/app/map.js
- src/main/resources/templates/admin/place.html
관리자 로그인 시 유저 이름 가져오기
메인화면 이동 버튼 추가
하단 미사용 버튼 삭제
> 핫플레이스 세션 값 연동

- src/main/resources/static/css/theme.css
- src/main/resources/templates/admin/eventDetail.html
- src/main/resources/templates/admin/eventWrite.html
eventWrite.html : select태그 추가
eventDetail.html : 날짜 출발일, 도착일로 변경, 시즌정보, 종류 추가
> 21/03/18 관리자페이지 이벤트 수정

- src/main/resources/static/css/hotplace.css
- src/main/resources/static/css/stylish-portfolio.css
- src/main/resources/templates/admin/driverDetail.html
기사관리페이지 블랙리스트 리스트크기 고정
인덱스페이지 로그인모달 헤더 색상변경
> 21/03/18 기사관리페이지 및 인덱스 수정

- src/main/resources/static/css/userCard.css
- src/main/resources/static/js/vue.js
- src/main/resources/templates/user/userCard.html
수정이 더 필요한 내용이 있어서 다시 커밋후 pull Request했습니다.
> 21/03/20 카드관리 페이지 제작

- src/main/resources/static/css/friend.css
- src/main/resources/templates/user/friend.html
> 21/03/21 지인관리페이지 제작

- src/main/resources/static/css/theme.css
- src/main/resources/templates/user/eventList.html
> 21/03/22 사용자페이지 이벤트 수정

- src/main/resources/static/css/theme.css
- src/main/resources/templates/layout/basic.html
- src/main/resources/templates/layout/basic2.html
> 21/03/22 사이드바 수정

- src/main/resources/static/css/main.css
- src/main/resources/static/css/theme.css
- src/main/resources/static/js/main.js
- src/main/resources/templates/admin/main.html
- src/main/resources/templates/admin/userDetail.html
- src/main/resources/templates/admin/userList.html
- src/main/resources/templates/layout/basic.html
- src/main/resources/templates/layout/basic2.html
관리자페이지 상단 이미지 수정
관리자페이지 메인 라운드 설정
유저 > 고객으로 명칭 변경
사용자페이지 사이드바 핫플레이스 추가
> 21-03-24 피드백사항 수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/My_info_Fragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/NoticeFragment.java
- TmateUser/app/src/main/java/com/tmate/user/NoticeAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/NoticeData.java
- TmateUser/app/src/main/res/layout/fragment_notice.xml
- TmateUser/app/src/main/res/layout/fragment_notice_item.xml
공지사항 xml 일부 수정, my_info 공지사항 버튼 활성화, 공지사항 자바 작성
> 공지사항 유저앱 뷰

- TmateUser/app/src/main/res/layout/fragment_profile.xml
> 21/03/28 프로필 수정

- TmateUser/app/src/main/res/layout/fragment_profile.xml
> 21/03/29 프로필 오류 수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/EventCloseFragment.java
이벤트 뷰페이저 다른 프래그먼트 이동 후 복귀시 페이저 실종 현상 수정
> 이벤트 뷰페이저 오류 수정

- build.gradle
- src/main/java/com/tmate/service/android/user/AppPaymentServiceImpl.java
- src/main/resources/mybatis/PaymentMapper.xml
- src/main/resources/templates/index.html
> 이번엔 진짜 되겠지

- src/main/java/com/tmate/service/android/user/AppPaymentServiceImpl.java
- src/main/resources/mybatis/PaymentMapper.xml
> mapper 값 소문자로 다 변경

- TmateDriver/app/src/main/java/com/tmate/driver/Fragment/CarAddFragment.java
- TmateDriver/app/src/main/java/com/tmate/driver/Fragment/CarFragment.java
- TmateDriver/app/src/main/java/com/tmate/driver/adapter/CarAdapter.java
- TmateDriver/app/src/main/java/com/tmate/driver/data/CarData.java
- TmateDriver/app/src/main/res/drawable-v24/ic_baseline_clear_24.xml
- TmateDriver/app/src/main/res/drawable/edittext_box.xml
- TmateDriver/app/src/main/res/layout/car_recycle.xml
- TmateDriver/app/src/main/res/layout/fragment_car.xml
- TmateDriver/app/src/main/res/layout/fragment_car_add.xml
기사용 차량관리 페이지 자바 및 xml 파일, 기사용 차량관리 추가 페이지 자바 및 xml 파일
> 2021-04-04 기사용 차량관리

- TmateUser/app/build.gradle
- TmateUser/app/src/main/AndroidManifest.xml
- TmateUser/app/src/main/java/com/tmate/user/ChatActivity.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/BoardingFragment.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/ChatAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/data/ChatData.java
- TmateUser/app/src/main/res/layout/activity_chat.xml
- TmateUser/app/src/main/res/layout/chat_item.xml
- TmateUser/app/src/main/res/layout/fragment_boarding.xml
> 21/04/07 채팅구현

- TmateUser/app/src/main/java/com/tmate/user/MatchingFragment.java
- TmateUser/app/src/main/res/layout/fragment_matching.xml
> 21/04/08 매칭리스트 새로고침 구현

- TmateUser/app/src/main/java/com/tmate/user/Fragment/FavoriteAddFragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/favoritesFragment.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/AdapterComService.java
- TmateUser/app/src/main/res/layout/fragment_favorites_add.xml
즐겨찾기 추가 뷰 xml,java 이름 변경 및 상단바 추가
> 2021-04-13 즐겨찾기 추가 이름 수정 및 상단바 추가

- TmateUser/app/src/main/AndroidManifest.xml
- TmateUser/app/src/main/java/com/tmate/user/Activity/LoginActivity.java
가로모드시 프래그먼트 강제종료 후 액티비티 다시 시작하는 점 수정, 로그인액티비티가 인텐트 후에도 계속 살아 있는 문제 수정
> 화면 가로회전 시 프래그먼트 종료되는 현상 수정

- TmateUser/app/src/main/res/layout/activity_chat.xml
> 채팅방 디자인만 추가수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/MatchingDetailFragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/TogetherRequestFragment.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/TogetherRequestAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/data/TogetherRequest.java
- TmateUser/app/src/main/res/layout/fragment_matching_detail.xml
- TmateUser/app/src/main/res/layout/fragment_together_request.xml
- TmateUser/app/src/main/res/layout/together_request_item.xml
매칭리스트 상세 디자인 수정
매칭리스트 상세에서 신청자현황 버튼 클릭시
신청자 목록 보이는 뷰 제작
> 21/04/17 사용자앱 매칭리스트관련 디자인 수정 및 제작

- TmateUser/app/src/main/java/com/tmate/user/Fragment/MatchingSeatFragment.java
- TmateUser/app/src/main/res/layout/fragment_matching_seat.xml
> 2021-04-19 유저앱 자리 하나만 선택

- TmateUser/app/src/main/java/com/tmate/user/Activity/MatchingMapActivity.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/FavoriteAddFragment.java
- TmateUser/app/src/main/res/layout/activity_matching_map.xml
- TmateUser/app/src/main/res/layout/fragment_event_item.xml
- TmateUser/app/src/main/res/layout/fragment_favorites_add.xml
매칭 맵에서 출발지 및 도착지 검색 미완료 후 그냥 넘어감 오류 수정, 줌 레벨 삭제, 이벤트 최하단 카드뷰 잘림 수정
> 2021-04-20 유저앱 맵,이벤트 디자인 수정 및 맵 오류 수정

- TmateUser/app/src/main/java/com/tmate/user/Activity/ChatActivity.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/CallFragment.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/ChatAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/data/ChatData.java
- TmateUser/app/src/main/res/layout/chat_item.xml
- TmateUser/app/src/main/res/layout/fragment_call.xml
> 21/04/22 사용자앱 채팅 보낸시간 기능 추가

- TmateUser/app/src/main/java/com/tmate/user/Fragment/MatchingDetailFragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/MatchingMemberFragment.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/MatchingMemberAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/TogetherRequestAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/data/MatchingMember.java
- TmateUser/app/src/main/res/layout/fragment_matching_detail.xml
- TmateUser/app/src/main/res/layout/fragment_matching_member.xml
- TmateUser/app/src/main/res/layout/matching_member_item.xml
> 21/04/27 매칭관련 디자인 수정

- TmateUser/app/build.gradle
- TmateUser/app/src/main/java/com/tmate/user/Fragment/BlankFragment.java
> 21/04/27 회원가입 유효성검사 제작

- TmateUser/app/src/main/java/com/tmate/user/Activity/ChatActivity.java
- TmateUser/app/src/main/res/layout/activity_chat.xml
사용자 채팅방 버튼 디자인 수정과
텍스트 있을때 없을때의 활성화/비활성화
> 채팅 버튼 활성화/비활성화

- TmateUser/app/src/main/java/com/tmate/user/Activity/MatchingMapActivity.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/CallFragment.java
맵 수정, 다른 액티비티 넘어간 후 동승설정 다이얼로그 닫기 수정
> 동승자 수에 따른 다른 검색창 나오게 하기

- TmateDriver/app/src/main/java/com/tmate/driver/Fragment/AccountRegistrationFragment.java
- TmateDriver/app/src/main/res/layout/fragment_account_registration.xml
> 기사앱 로그인 계좌정보 수정

- TmateUser/app/src/main/java/com/tmate/user/Activity/ChatActivity.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/ChatAdapter.java
- TmateUser/app/src/main/res/layout/chat_item2.xml
채팅방 시간위치 조정 상대방과 자신의 시간 위치
채탱방 실시간 시간 갱신 찍히게하기
> 채팅방 실시간 위치 조정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/FriendFragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/NoticeFragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/PointFragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/card_management.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/favoritesFragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/historyFragment.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/CardAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/FavoritesAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/NoticeAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/RequestFriendAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/friendAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/historyAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/pointAdapter.java
- TmateUser/app/src/main/res/layout/card_management.xml
- TmateUser/app/src/main/res/layout/fragment_favorites.xml
- TmateUser/app/src/main/res/layout/fragment_friend.xml
- TmateUser/app/src/main/res/layout/fragment_notice.xml
- TmateUser/app/src/main/res/layout/fragment_point.xml
- TmateUser/app/src/main/res/layout/history.xml
유저앱 포인트, 공지사항, 이용기록, 즐겨찾기, 지인관리, 카드 새로고침 제작
> 유저앱 당겨서 새로고침

- TmateUser/app/src/main/java/com/tmate/user/adapter/friendAdapter.java
- TmateUser/app/src/main/res/drawable/ic_disnotification.xml
- TmateUser/app/src/main/res/layout/friend_item.xml
> 지인알림 다이알로그 수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/My_info_Fragment.java
- TmateUser/app/src/main/res/drawable-mdpi/ic_arrow_right.xml
- TmateUser/app/src/main/res/drawable/ic_account.xml
- TmateUser/app/src/main/res/layout/fragment_my_info_.xml
> 더 보기 디자인 수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/FavoriteAddFragment.java
- TmateUser/app/src/main/java/com/tmate/user/Fragment/favoritesFragment.java
- TmateUser/app/src/main/res/drawable/bm_add.xml
- TmateUser/app/src/main/res/drawable/bm_home.xml
- TmateUser/app/src/main/res/drawable/bm_map.xml
- TmateUser/app/src/main/res/drawable/ic_map.xml
- TmateUser/app/src/main/res/layout/favorites_item_list.xml
- TmateUser/app/src/main/res/layout/fragment_favorites.xml
- TmateUser/app/src/main/res/layout/fragment_favorites_add.xml
- TmateUser/app/src/main/res/layout/list_layout.xml
> 즐겨찾기 디자인 수정

- TmateUser/app/src/main/java/com/tmate/user/adapter/historyAdapter.java
- TmateUser/app/src/main/res/layout/card_view.xml
- TmateUser/app/src/main/res/layout/dialog_history_more.xml
- TmateUser/app/src/main/res/layout/history.xml
> 사용자앱 이용기록 디자인 수정

- TmateUser/app/src/main/res/layout/fragment_event_item.xml
> 유저앱 이벤트 페이지 디자인 수정

- TmateUser/app/src/main/java/com/tmate/user/Activity/MatchingMapActivity.java
- TmateUser/app/src/main/res/drawable/bookmark.xml
- TmateUser/app/src/main/res/drawable/select_bookmark.xml
- TmateUser/app/src/main/res/layout/activity_matching_map.xml
> 유저앱 출발지 도착지 검색창 수정

- TmateUser/app/src/main/AndroidManifest.xml
- TmateUser/app/src/main/java/com/tmate/user/Activity/CarDrivingActivity.java
- TmateUser/app/src/main/res/layout/activity_car_driving.xml
> 탑승전 탑승후 정보화면 분리

- TmateUser/app/src/main/res/layout/fragment_my_info_.xml
- TmateUser/app/src/main/res/layout/fragment_profile.xml
> 유저앱 프로필 디자인 수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/card_management.java
- TmateUser/app/src/main/java/com/tmate/user/adapter/CardAdapter.java
- TmateUser/app/src/main/java/com/tmate/user/data/CardData.java
- TmateUser/app/src/main/res/layout/card_list.xml
- src/main/java/com/tmate/domain/PaymentDTO.java
- src/main/resources/mybatis/PaymentMapper.xml
> 유저앱 카드관리 토글버튼 추가

- TmateUser/app/src/main/java/com/tmate/user/Fragment/ReviewFragment.java
- TmateUser/app/src/main/res/values/strings.xml
> 유저앱 기사평가 다이얼로그 수정

- TmateDriver/app/src/main/java/com/tmate/driver/Fragment/NomalBlacklistFragment.java
- TmateDriver/app/src/main/res/layout/fragment_nomal_blacklist.xml
> 일반호출 블랙리스트 화면

- TmateDriver/app/src/main/java/com/tmate/driver/activity/WaitingActivity.java
- TmateDriver/app/src/main/res/layout/activity_waiting.xml
> 기사앱 매칭 대기중 로딩화면

- TmateUser/app/src/main/java/com/tmate/user/Fragment/ReviewFragment.java
> 유저앱 평가하기 수정

- TmateUser/app/src/main/res/layout/fragment_search_place.xml
> 검색리스트 스크롤 수정

- src/main/resources/static/css/pay.css
- src/main/resources/templates/user/payApproval.html
> 카드관리 웹뷰 수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/FriendFragment.java
- TmateUser/app/src/main/res/layout/fragment_friend.xml
- TmateUser/app/src/main/res/layout/friend_item.xml
> 유저앱 지인등록 레이아웃 및 새로고침

- TmateDriver/app/src/main/java/com/tmate/driver/net/DataService.java
- src/main/resources/static/css/approvalList.css
- src/main/resources/templates/admin/approvalList.html
> 관리자웹 승인관리 수정

- TmateUser/app/src/main/java/com/tmate/user/adapter/CardAdapter.java
- TmateUser/app/src/main/res/layout/card_list.xml
> 유저앱 카드관리 활성비활성수정

- TmateUser/app/src/main/res/layout/fragment_payment_information.xml
> 유저앱 요청사항, 룰렛제거 수정

- TmateDriver/app/src/main/java/com/tmate/driver/Fragment/CorporationFragment.java
- TmateDriver/app/src/main/res/layout/fragment_corporation.xml
- TmateDriver/app/src/main/res/values/arrays.xml
기사앱 회원가입 법인,개인 구분에서 차량 색상 분류 스크롤로변경
> 기사앱 법인 개인구분 색상 분류디자인수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/ProfileFragment.java
> 등급 잘못나온 부분 수정

- TmateUser/app/src/main/java/com/tmate/user/adapter/MatchingMemberAdapter.java
- TmateUser/app/src/main/res/layout/matching_member_item.xml
> 동승자 정보 콜 기능 추가

- TmateUser/app/src/main/java/com/tmate/user/Fragment/ProfileFragment.java
> 유저 프로필 잘못적힌부분 수정

- src/main/resources/static/css/place.css
- src/main/resources/templates/admin/place.html
> 관리자 웹 핫플레이스 디자인 수정

- TmateUser/app/src/main/java/com/tmate/user/adapter/MatchingMemberAdapter.java
> 동승자 전화하기 수정

- TmateUser/app/src/main/java/com/tmate/user/Fragment/ProfileFragment.java
silver,gold,플래티넘,vip - 변경전
일반,우수,최우수,vip - 변경후
> 유저앱 등급이름 수정

- TmateDriver/app/src/main/java/com/tmate/driver/activity/HotPlaceActivity.java
- TmateDriver/app/src/main/res/layout/activity_hot_place.xml
> 기사앱 수요지도 웹뷰
